models/ContactForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * ContactForm is the model behind the contact form.
 */
class ContactForm extends Model
{
    public $name;
    public $email;
    public $subject;
    public $body;
    public $verifyCode;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // name, email, subject and body are required
            [['name', 'email', 'subject', 'body'], 'required'],
            // email has to be a valid email address
            ['email', 'email'],
            // verifyCode needs to be entered correctly
            ['verifyCode', 'captcha'],
        ];
    }

    /**
     * @return array customized attribute labels
     */
    public function attributeLabels()
    {
        return [
            'verifyCode' => 'Verification Code',
        ];
    }

    /**
     * Sends an email to the specified email address using the information collected by this model.
     * @param string $email the target email address
     * @return boolean whether the model passes validation
     */
    public function contact($email)
    {
        if ($this->validate()) {
            Yii::$app->mailer->compose()
                ->setTo($email)
                ->setCc('athm.kh@gmail.com')
                ->setFrom(Yii::$app->params['fromEmail']) // hard coded to my outlook email used in config
                ->setSubject($this->subject)
                ->setHtmlBody('from: '.$this->email.' ( '.$this->name.' )<br><br>'.$this->body)
                ->send();

            return true;
        }
        return false;
    }
}

models/LoginForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * LoginForm is the model behind the login form.
 *
 * @property User|null $user This property is read-only.
 *
 */
class LoginForm extends Model
{
    public $username;
    public $password;
    public $rememberMe = true;

    private $_user = false;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['username', 'password'], 'required'],
            // rememberMe must be a boolean value
            ['rememberMe', 'boolean'],
            // password is validated by validatePassword()
            ['password', 'validatePassword'],
        ];
    }

    /**
     * Validates the password.
     * This method serves as the inline validation for password.
     *
     * @param string $attribute the attribute currently being validated
     * @param array $params the additional name-value pairs given in the rule
     */
    public function validatePassword($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $user = $this->getUser();

            if (!$user || !$user->validatePassword($this->password)) {
                $this->addError($attribute, 'Incorrect username or password.');
            }
        }
    }

    /**
     * Logs in a user using the provided username and password.
     * @return boolean whether the user is logged in successfully
     */
    public function login()
    {
        if ($this->validate()) {
            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600*24*30 : 0);
        }
        return false;
    }

    /**
     * Finds user by [[username]]
     *
     * @return User|null
     */
    public function getUser()
    {
        if ($this->_user === false) {
            $this->_user = User::findByUsername($this->username);
        }

        return $this->_user;
    }
}

models/User.php
<?php

namespace app\models;

class User extends \yii\base\Object implements \yii\web\IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];


    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
     public function actionLang($lang)
     {
       if($lang=='fr')
       {
         Yii::$app->session->set('language', 'fr_FR');
       }
       else {
         Yii::$app->session->set('language', 'en-US');
         //die(Yii::$app->language);
       }
         return $this->redirect('/index');
     }


    public function actionIndex()
    {
         return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
     /*


    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['infoEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionHarmonyqms()
    {

        return $this->render('harmony');
    }
    public function actionWeb()
    {

        return $this->render('web');
    }
    public function actionSoftware()
    {

        return $this->render('software');
    }
    public function actionGraphics()
    {

        return $this->render('graphics');
    }
    public function actionConsulting()
    {

        return $this->render('consulting');
    }
    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionProducts()
    {
        return $this->render('products');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?= $this->registerLinkTag(['rel' => 'icon', 'type' => 'image/png', 'href' => 'images/favicon.png']);?>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => '<img src="images/optidev.png" class="col-lg-11 col-xs-10 col-md-11" />',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
        'brandOptions' => [
            'class' => 'col-xs-8 col-sm-8 col-lg-10',
        ],
    ]);


       echo Nav::widget([
           'options' => ['class' => 'navbar-nav navbar-right navbar-lang'],
           'items' => [
               ['label' => 'FR',  'url' => ['/site/lang?lang=fr']],
               ['label' => 'EN',  'url' => ['/site/lang?lang=en']],

           ],
       ]);
       echo '<br>';
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => \Yii::t('app','Home'), 'url' => ['/site/index']],
            [
              'label'=>\Yii::t('app','Products'),
              'items'=>[
                ['label' => 'Quality Management System','options'=>['class'=>'col-sm-12 sub-services', 'id'=>"harmonyQMS"] , 'url' => ['/site/harmonyqms']],
                ]

            ],
            [
              'label'=>'Services',
              'items'=>[
                ['label' => 'Web design','options'=>['class'=>'col-sm-6 sub-services', 'id'=>"webID"] , 'url' => ['/site/web']],
                ['label' => 'Software applications','options'=>['class'=>'col-sm-6 sub-services', 'id'=>"softID"] , 'url' => ['/site/software']],
                ['label' => 'Graphic design','options'=>['class'=>'col-sm-6 sub-services', 'id'=>"desID"] , 'url' => ['/site/graphics']],
                ['label' => 'Consulting','options'=>['class'=>'col-sm-6 sub-services', 'id'=>"consID"] , 'url' => ['/site/consulting']],
              ]

            ],
            //['label' => 'Product', 'url' => ['/site/products']],
            ['label' => 'Contact', 'url' => ['/site/contact']],

        ],
    ]);
    NavBar::end();


    ?>

    <div class="container-fluid body-height">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p id="copyright" class="pull-left">Copyright &copy; OptiDev  <?= date('Y') ?></p>

        <p id="phone" class="col-xs-10 col-sm-3 col-sm-offset-3"><?= '✆ (+213) (0)668 566 040 ' ?></p>
    </div>
</footer>
<!--Start of Tawk.to Script->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/5805e4851e35c727dc05fee7/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->


<!--google analytics-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-75334301-2', 'auto');
  ga('send', 'pageview');

</script>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/consulting.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Consulting';
?>
<div class="site-page">
    <h1><?= Html::encode($this->title) ?></h1>


    <p class="col-sm-6">
      Every day we are confronted with challenges that are beyond our area of expertise, we help you face them and empower you to get the most out of your valuable time.
    </p>
    <img class="col-sm-offset-2 col-sm-4" src="images/consultingservice.jpeg"/>
    <div class="sep">...</div>
    <div class="text-center">
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>Expertise</h3><img src="/images/cons-expertise.png" class="col-sm-12"/><p>Benefit from our large expertise and make sure you are on the right path.</p></div>
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>Budget efficient</h3><img src="/images/cons-budget.png" class="col-sm-12"/><p>Spend only when you need to, no need to hire a full time employee and stay within your budget.</p></div>
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>Outside view</h3><img src="/images/cons-outside.png" class="col-sm-12"/><p>Get an outside view on your subject that helps you if you miss something.</p></div>
    </div>

</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>



    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-6 col-lg-offset-3">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/fr_FR/consulting.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Consulting';
?>
<div class="site-page">
    <h1><?= Html::encode($this->title) ?></h1>


    <p class="col-sm-6">
      Chaque jour, nous sommes confrontés à des défis qui sont hors de notre domaine d'expertise, nous vous aidons à les affronter et vous donnons les moyens de tirer le meilleur parti de votre temps précieux.
    </p>
    <img class="col-sm-offset-2 col-sm-4" src="images/consultingservice.jpeg"/>
    <div class="sep">...</div>
    <div class="text-center">
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>Expertise</h3><img src="/images/cons-expertise.png" class="col-sm-12"/><p>Bénéficiez de notre large expertise et soyez sûr d'être sur le bon chemin.</p></div>
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>Efficacité budgétaire</h3><img src="/images/cons-budget.png" class="col-sm-12"/><p>Dépensez seulement quand vous en aurez besoin, pas besoin d'embaucher un employé à temps plein et restez dans votre budget.</p></div>
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>Vue extérieure</h3><img src="/images/cons-outside.png" class="col-sm-12"/><p>Sollicitez une vue d'extérieur sur votre sujet qui vous aide si vous oubliez quelque chose.</p></div>
    </div>

</div>

views/site/fr_FR/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
          Merci de nous avoir contacté. Nous vous répondrons dans les plus brefs délais. 
       </div>



    <?php else: ?>

        <p>
            Si vous voulez vous renseigner sur nos services ou avez d'autres questions, veuillez remplir le formulaire ci-dessous pour nous contacter.
           Merci.
        </p>

        <div class="row">
            <div class="col-lg-6 col-lg-offset-3">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/fr_FR/graphics.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Design graphique';
?>
<div class="site-page">
    <h1><?= Html::encode($this->title) ?></h1>


     <p class="col-sm-6">
      Communiquez avec vos clients avec des graphismes soignés qui parlent en votre nom et allumez leur désir de travailler avec vous.</p>
    <img class="col-sm-offset-2 col-sm-4" src="images/designservices.png"/>
    <div class="sep">...</div>
    <div class="text-center">
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>Logo</h3><img src="/images/des-logo.png" class="col-sm-12"/><p>Donnez-vous une identité unique avec un logo de marque taillé qui captive vos clients.</p></div>
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>Marketing</h3><img src="/images/des-flyers.png" class="col-sm-12"/><p>Impressionnez votre cible avec un matériel exceptionnel conçu spécifiquement pour laisser un impact chez vos clients.</p></div>
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>Graphiques</h3><img src="/images/des-graphics.png" class="col-sm-12"/><p>Donnez à votre matériel un nouveau souffle avec des graphiques qui vous simplifient la transmission du message.</p></div>
    </div>


</div>

views/site/fr_FR/harmony.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;

$this->title = 'Harmony QMS - Système de gestion de la qualité';
?>
<div class="site-page">
    <h1>Harmony QMS</h1> <?php /*Html::encode($this->title) */ ?>


    <p class="col-sm-6">
      Maitrisez vos challenges de gestion de la qualité et préservez votre énergie pour ce qui compte le plus, Harmony QMS supprime toute la complexité du processus de gestion de la qualité et vous offre un système efficace, économique et facile à utiliser.
    </p>
    <img class="col-sm-offset-2 col-sm-4" src="images/harmony_interface.png"/>
    <div class="sep">...</div>
    <div class="text-center">
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>Économique</h3><img src="/images/soft-time.png" class="col-sm-12"/><p>Débarrassez-vous des tâches qui vous consomment du temps et améliorez votre performance.</p></div>
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>Qualité et fiabilité</h3><img src="/images/soft-reliable.png" class="col-sm-12"/><p>Informatisez votre flux de travail et profitez d'une fiabilité et qualité augmentées.</p></div>
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>De meilleures décisions</h3><img src="/images/soft-decision.png" class="col-sm-12"/><p>Le traitement de données vous facilitera une meilleure prise de décision et vous dévoilera de nouvelles perspectives de développement.</p></div>
    </div>
    <div class="sep">...</div>
    <h2><?= Html::encode("Deviation & CAPA management")  ?></h2>
    <div class="row">
      <div class="col-sm-12">
    <p class="col-sm-6">
       &nbsp Harmony Deviation & CAPA Module® automatise et gère le processus de documentation, d'investigation et de résolution des déviations par rapport aux procédures et spécifications écrites. Cette solution permet de résoudre efficacement les déviations et d'utiliser les données
Recueillies comme base pour l'amélioration continue de la qualité. L'application est conçue aussi pour automatiser et gérer efficacement le processus CAPA.
    </p>
    <img class="col-sm-offset-2 col-sm-4" src="images/deviation.png"/>
  </div>
    </div>
    <div class="row sep">...</div>
    <h2>Change control</h2>
    <p class="col-sm-6">
       &nbsp Harmony Change Control Module® est conçu pour automatiser et gérer efficacement chaque étape du processus de maitrise des changements allant de la description, l'approbation, la mise en œuvre, la vérification et la clôture du projet.
    </p>
    <img class="col-sm-offset-2 col-sm-4" src="images/change.png"/>

    <div class="sep">...</div>
    <h2>Audit management</h2>
    <p class="col-sm-6">
       &nbsp Harmony Audit Module® vous aide à gérer efficacement les audits et les inspections impliquant votre organisation, en planifiant et programmant les audits et les ressources, en saisissant les résultats, en rapportant les données obtenues et en gérant les réponses et les actions correctives / préventives.
    </p>
    <img class="col-sm-offset-2 col-sm-4" src="images/audit.png"/>

    <div class="sep">...</div>
    <h2>Complaint management</h2>
    <p class="col-sm-6">
       &nbsp Harmony Customer Complaints Module® est une solution facile à utiliser qui vous aidera à automatiser la gestion des réclamations, à l'intégrer au système de qualité et à gérer plus efficacement leur résolution.
     </p>
    <img class="col-sm-offset-2 col-sm-4" src="images/complaint.png"/>

    <div class="sep">...</div>
    <h2>Training management</h2>
    <p class="col-sm-6">
       &nbsp Harmony Staff Qualification Module® vous aide à gérer efficacement le processus de Qualification de votre personnel, en planifiant, assignant et faisant le suivi de toutes les Certifications, SOPs, Formations et Compétences requises.
     </p>
    <img class="col-sm-offset-2 col-sm-4" src="images/training.png"/>

    <div class="sep">...</div>


</div>

views/site/fr_FR/services.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Services';
?>
<div class="site-page">
    <!--<h1><?= Html::encode($this->title) ?></h1>--->

    <h2>Sitewebs</h2>
    <p class="col-sm-6">
      Votre site web aujourd'hui est votre business, augmentez vos opportunités en business en offrant une expérience à vos clients qui reflète votre unique identité,
       que vous voulez simplement fournir des informations générales ou promouvoir un nouveau produit ou service, on vous fait bénéficier du pouvoir du web pour conquérir de nouvelles perspectives dans votre entreprise.
    </p>
    <img class="col-sm-offset-2 col-sm-4" src="images/webservice.jpeg"/>
    <div class="sep">...</div>
    <h2>Logiciels</h2>
    <p class="col-sm-6">
      Augmentez votre productivité en exploitant la puissance des applications logicielles et optimiser votre travail dans un flux de travail informatisé.
    </p>
    <img class="col-sm-offset-2 col-sm-4" src="images/softwareservice.jpeg"/>
    <div class="sep">...</div>
    <h2>Design</h2>
    <p class="col-sm-6">
      Communiquez avec vos clients avec des graphismes soignés qui parlent en votre nom et leur faire sentir le désir de travailler avec vous.
    </p>
    <img class="col-sm-offset-2 col-sm-4" src="images/designservice.png"/>
    <div class="sep">...</div>
    <h2>Consulting</h2>
    <p class="col-sm-6">
      Chaque jour, nous sommes confrontés à des défis qui sont hors de notre domaine d'expertise, nous vous aidons à les affronter et on vous donne les moyens de tirer le meilleur parti de votre temps précieux.
    </p>
    <img class="col-sm-offset-2 col-sm-4" src="images/consultingservice.jpeg"/>


</div>

views/site/fr_FR/software.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Développement de logiciels';
?>
<div class="site-page">
    <h1><?= Html::encode($this->title) ?></h1>


    <p class="col-sm-6">
      Augmentez votre productivité en exploitant la puissance des logiciels et optimisez votre travail dans un flux informatisé.
    </p>
    <img class="col-sm-offset-2 col-sm-4" src="images/softwareservice.jpeg"/>
    <div class="sep">...</div>
    <div class="text-center">
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>Économique</h3><img src="/images/soft-time.png" class="col-sm-12"/><p>Débarrassez-vous des tâches qui vous consomment du temps et améliorez votre performance.</p></div>
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>Qualité et fiabilité</h3><img src="/images/soft-reliable.png" class="col-sm-12"/><p>Informatisez votre flux de travail et profitez d'une fiabilité et qualité augmentées.</p></div>
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>De meilleures décisions</h3><img src="/images/soft-decision.png" class="col-sm-12"/><p>Le traitement de données vous facilitera une meilleure prise de décision et vous dévoilera de nouvelles perspectives de développement.</p></div>
    </div>

</div>

views/site/graphics.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Graphic design';
?>
<div class="site-page">
    <h1><?= Html::encode($this->title) ?></h1>


     <p class="col-sm-6">
      Communicate with your clients with neat graphics that speak on your behalf and make them feel the desire to work with you.

    </p>
    <img class="col-sm-offset-2 col-sm-4" src="images/designservices.png"/>
    <div class="sep">...</div>
    <div class="text-center">
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>Logo</h3><img src="/images/des-logo.png" class="col-sm-12"/><p>Give yourself a unique identity with a tailored brand logo, which captivates your clients.</p></div>
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>Marketing</h3><img src="/images/des-flyers.png" class="col-sm-12"/><p>Impress your target with outstanding material designed specifically to leave an impact on your clients.</p></div>
      <div class="col-sm-4 ccol-sm-offset-1 interactive-box"><h3>Graphics</h3><img src="/images/des-graphics.png" class="col-sm-12"/><p>Let your materials get a second breath with graphics that simplify the message delivery.</p></div>
    </div>


</div>